---
- name: Playbook 3 - Backup AdGuard Home i Live Verification
  hosts: agh
  become: yes
  vars:
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    remote_backup_dir: "/tmp/backups"
    test_restore_dir: "/tmp/agh_test_instance"
    backup_dest_host: "ansible"

  tasks:
    # --- NOWA SEKCJA: NAPRAWA BŁĘDU Z FILMU/SCREENA ---
    - name: Naprawa struktury folderów na serwerze Ansible
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Usuwanie błędnego pliku/folderu backups (czyszczenie)
          file:
            path: "{{ remote_backup_dir }}"
            state: absent

        - name: Tworzenie poprawnego folderu na backupy
          file:
            path: "{{ remote_backup_dir }}"
            state: directory
            mode: '0777'

    # --- CZĘŚĆ 1: ROBIENIE BACKUPU NA SERWERZE AGH ---
    - name: Sekcja Backup
      block:
        - name: Pakowanie plików AdGuard Home
          archive:
            path: "{{ agh_dir }}"
            dest: "{{ tmp_archive }}"
            format: gz

        - name: Wysyłka backupu na serwer Ansible
          fetch:
            src: "{{ tmp_archive }}"
            dest: "{{ remote_backup_dir }}/"
            flat: no # To stworzy podfoldery, ale find je znajdzie

        - name: Sprzątanie pliku tymczasowego na AGH
          file:
            path: "{{ tmp_archive }}"
            state: absent
      rescue:
        - name: Powiadomienie o błędzie backupu
          debug:
            msg: "BŁĄD: Nie udało się spakować AdGuarda!"

    # --- CZĘŚĆ 2: WERYFIKACJA NA SERWERZE ANSIBLE ---
    - name: Sekcja Weryfikacja Live
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Pies gończy - szukanie pliku backupu
          find:
            paths: "{{ remote_backup_dir }}"
            patterns: "*.tar.gz"
            recurse: yes
          register: found_backups

        - name: Sprawdzenie czy pies znalazł paczkę
          fail:
            msg: "Nie znaleziono pliku backupu w {{ remote_backup_dir }}!"
          when: found_backups.matched == 0

        - name: Przygotowanie folderu do testu
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0755'

        - name: Rozpakowanie backupu
          unarchive:
            src: "{{ found_backups.files[0].path }}"
            dest: "{{ test_restore_dir }}"
            remote_src: yes

        - name: Uruchomienie testowego AdGuarda
          shell: |
            pkill -f "AdGuardHome" || true
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome > /tmp/agh_test_log.txt 2>&1 &
          async: 15
          poll: 0

        - name: Czekamy na port 3000
          pause:
            seconds: 10

        - name: TEST PANELU WWW
          uri:
            url: "http://127.0.0.1:3000"
            status_code: 200
          register: web_test

        - name: Sukces
          debug:
            msg: "W KOŃCU! Backup zweryfikowany. Plik był w: {{ found_backups.files[0].path }}"

      rescue:
        - name: Powiadomienie o trupie
          debug:
            msg: "ALARM! Coś poszło nie tak przy odtwarzaniu!"
