---
- name: "Backup AdGuard Home - Operacja Ratunkowa"
  hosts: agh  # Maszyna AGH_{nazwisko}
  become: yes
  vars:
    # Tu wpisz gdzie chcesz to trzymać na maszynie Ansible_{nazwisko}
    backup_dest_on_ansible: "/tmp/agh_kopia_bezpieczenstwa.tar.gz"
  tasks:
    - name: "1. Sprawdzam czy katalog AdGuarda w ogóle żyje"
      stat:
        path: /adguardhome
      register: adg_stat

    - name: "BŁĄD: Brak katalogu źródłowego"
      fail:
        msg: "Ej! /adguardhome nie istnieje! Kopia nie wypali."
      when: not adg_stat.stat.exists

    - name: "2. Pakuję AdGuarda do jednego wora (tar.gz)"
      archive:
        path: /adguardhome
        dest: /tmp/adguard_backup.tar.gz
        format: gz
      register: archive_result

    - name: "3. Przerzucam paczkę do bazy (Maszyna Ansible)"
      fetch:
        src: /tmp/adguard_backup.tar.gz
        dest: "{{ backup_dest_on_ansible }}"
        flat: yes
      register: fetch_result

    - name: "4. Sprzątam śmieci na maszynie AGH"
      file:
        path: /tmp/adguard_backup.tar.gz
        state: absent

    - name: "Wypisz mi gdzie dokladnie to zapisales"
      debug:
        msg: "Plik powinien byc tutaj: {{ backup_dest_on_ansible }}"

# Sekcja powiadomień w razie wtopy
  post_tasks:
    - name: "Powiadomienie o sukcesie (opcjonalnie do logów)"
      debug:
        msg: "Backup zrobiony i wysłany do {{ backup_dest_on_ansible }}"
      when: fetch_result is succeeded

# Jeśli chcesz wysłać maila/notyfikację bezpośrednio z Ansible w razie błędu:
    - name: "Wysyłanie powiadomienia o błędzie"
      uri:
        url: "https://ntfy.sh/twoj_unikalny_kanal_powiadomien" # Przykład darmowego ntfy.sh
        method: POST
        body: "ALARM! Backup AdGuarda na maszynie {{ inventory_hostname }} wywalił się na plecy!"
      when: fetch_result is failed
