---
- name: Playbook 3 - Backup AdGuard Home i Live Verification
  hosts: agh
  become: yes
  vars:
    # Ścieżka źródłowa na serwerze AGH
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    
    # Ścieżki na serwerze Ansible (kontrolerze)
    remote_backup_dir: "/tmp/backups"
    # Gdzie postawimy testową instancję do weryfikacji
    test_restore_dir: "/tmp/agh_test_instance"
    
    # Nazwa hosta kontrolera w Twoim inwentarzu
    backup_dest_host: "ansible"

  tasks:
    # --- CZĘŚĆ 1: ROBIENIE BACKUPU NA SERWERZE AGH ---
    - name: Sekcja Backup
      block:
        - name: Pakowanie plików AdGuard Home
          archive:
            path: "{{ agh_dir }}"
            dest: "{{ tmp_archive }}"
            format: gz

        - name: Wysyłka backupu na serwer Ansible
          fetch:
            src: "{{ tmp_archive }}"
            dest: "{{ remote_backup_dir }}/"
            flat: no # Zostawiamy no, bo find i tak go znajdzie, a tak jest bezpieczniej dla uprawnień

        - name: Sprzątanie pliku tymczasowego na AGH
          file:
            path: "{{ tmp_archive }}"
            state: absent

      rescue:
        - name: Powiadomienie o błędzie backupu
          debug:
            msg: "BŁĄD KRYTYCZNY: Nie udało się spakować AdGuarda na serwerze źródłowym!"

    # --- CZĘŚĆ 2: WERYFIKACJA NA SERWERZE ANSIBLE (DELEGACJA) ---
    - name: Sekcja Weryfikacja Live
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Pies gończy - szukanie pliku backupu
          find:
            paths: "{{ remote_backup_dir }}"
            patterns: "*.tar.gz"
            recurse: yes
          register: found_backups

        - name: Sprawdzenie czy pies znalazł paczkę
          fail:
            msg: "Nie znaleziono pliku backupu w {{ remote_backup_dir }}!"
          when: found_backups.matched == 0

        - name: Przygotowanie folderu do testowego odpalenia
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0755'

        - name: Rozpakowanie backupu na serwerze Ansible
          unarchive:
            src: "{{ found_backups.files[0].path }}"
            dest: "{{ test_restore_dir }}"
            remote_src: yes

        - name: Uruchomienie testowej instancji AdGuarda w tle
          shell: |
            pkill -f "AdGuardHome" || true
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome > /tmp/agh_test_log.txt 2>&1 &
          async: 15
          poll: 0

        - name: Chwila cierpliwości (czekamy na start portu 3000)
          pause:
            seconds: 10

        - name: TEST PANELU WWW - Czy strona działa?
          uri:
            url: "http://127.0.0.1:3000"
            status_code:
