---
- name: Playbook 3 - Backup AdGuard Home i Live Verification
  hosts: agh
  become: yes
  vars:
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    test_restore_dir: "/tmp/agh_test_instance"
    backup_dest_host: "ansible"

  tasks:
    # --- CZĘŚĆ 1: BACKUP NA AGH ---
    - name: Pakowanie plikow AdGuard
      archive:
        path: "{{ agh_dir }}"
        dest: "{{ tmp_archive }}"
        format: gz

    - name: Sciaganie backupu do kontrolera Semaphore
      fetch:
        src: "{{ tmp_archive }}"
        dest: "./agh_final_backup.tar.gz"
        flat: yes

    # --- CZĘŚĆ 2: WERYFIKACJA NA SERWERZE ANSIBLE ---
    - name: Sekcja Weryfikacja
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Przygotowanie folderu testu
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0777'

        - name: Wyslanie pliku na maszyne docelowa
          copy:
            src: "./agh_final_backup.tar.gz"
            dest: "/tmp/agh_final_backup.tar.gz"

        - name: Rozpakowanie backupu
          unarchive:
            src: "/tmp/agh_final_backup.tar.gz"
            dest: "{{ test_restore_dir }}"
            remote_src: yes

        - name: Znajdz binarke AdGuardHome
          find:
            paths: "{{ test_restore_dir }}"
            patterns: "AdGuardHome"
            recurse: yes
            file_type: file
          register: agh_found

        - name: NADAWANIE UPRAWNIEN WYKONYWANIA (CHMOD +X)
          file:
            path: "{{ agh_found.files[0].path }}"
            mode: '0755'
          when: agh_found.matched > 0

        - name: Uruchomienie testowe (Tryb bezpośredni)
          shell: |
            pkill -f "AdGuardHome" || true
            sleep 2
            cd {{ agh_found.files[0].path | dirname }}
            # Odpalamy bezpośrednio z pełną ścieżką
            nohup ./AdGuardHome --no-check-update -w . -p 3000 > /tmp/agh_test_log.txt 2>&1 &
          async: 45
          poll: 0
          when: agh_found.matched > 0

        - name: Czekamy na port 3000
          pause:
            seconds: 20

        - name: TEST PORTU 3000
          wait_for:
            host: 127.0.0.1
            port: 3000
            state: started
            timeout: 25

        - name: Sukces
          debug:
            msg: "WYGRANA! System wstal z backupu."

      rescue:
        - name: Wyswietl logi binarne (jeśli powstały)
          command: "cat /tmp/agh_test_log.txt"
          register: startup_logs
          ignore_errors: yes

        - name: Raport bledu
          debug:
            msg: 
              - "Padlo na ostatniej prostej."
              - "Logi binarne: {{ startup_logs.stdout_lines | default('Brak logów w pliku') }}"
