---
- name: Playbook 3 - Backup AdGuard Home i Live Verification
  hosts: agh
  become: yes
  vars:
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    remote_backup_dir: "/tmp/backups"
    remote_backup_full_path: "/tmp/backups/agh_backup.tar.gz"
    test_restore_dir: "/tmp/agh_test_instance"
    backup_dest_host: "ansible"

  tasks:
    # --- KROK 0: NAPRAWA FOLDERÓW NA SERWERZE ANSIBLE ---
    - name: Reset folderu backupów na serwerze Ansible
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      file:
        path: "{{ remote_backup_dir }}"
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    # --- KROK 1: BACKUP NA AGH ---
    - name: Sekcja Backup
      block:
        - name: Pakowanie plików AdGuard Home
          archive:
            path: "{{ agh_dir }}"
            dest: "{{ tmp_archive }}"
            format: gz

        - name: Wysyłka backupu (Wymuszenie płaskiej struktury)
          fetch:
            src: "{{ tmp_archive }}"
            dest: "{{ remote_backup_full_path }}"
            flat: yes # TO JEST KLUCZ - plik wyląduje dokładnie tam, gdzie chcemy

        - name: Sprzątanie na AGH
          file:
            path: "{{ tmp_archive }}"
            state: absent
      rescue:
        - name: Powiadomienie o błędzie backupu
          debug: msg="BŁĄD: Nie udało się spakować AdGuarda!"

    # --- KROK 2: WERYFIKACJA NA ANSIBLE ---
    - name: Sekcja Weryfikacja Live
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Szukanie pliku (Pies gończy v3.0)
          find:
            paths: "{{ remote_backup_dir }}"
            patterns: "agh_backup.tar.gz"
            recurse: yes
            file_type: file
          register: found_backups

        - name: Sprawdzenie czy plik istnieje
          fail:
            msg: "Nadal nie widzę pliku w {{ remote_backup_dir }}! Sprawdź uprawnienia."
          when: found_backups.matched == 0

        - name: Przygotowanie folderu testu
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0755'

        - name: Rozpakowanie backupu
          unarchive:
            src: "{{ found_backups.files[0].path }}"
            dest: "{{ test_restore_dir }}"
            remote_src: yes

        - name: Uruchomienie testowe w tle
          shell: |
            pkill -f "AdGuardHome" || true
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome > /tmp/agh_test_log.txt 2>&1 &
          async: 15
          poll: 0

        - name: Czekamy na port 3000
          pause:
            seconds: 10

        - name: TEST PANELU WWW
          uri:
            url: "http://127.0.0.1:3000"
            status_code: 200
          register: web_test

        - name: Sukces
          debug:
            msg: "WYGRANA! Plik znaleziony i przetestowany: {{ found_backups.files[0].path }}"

      rescue:
        - name: Powiadomienie o trupie
          debug: msg="ALARM! Weryfikacja nie przeszła!"
