---
- name: Backup AdGuard Home i pełna weryfikacja
  hosts: agh
  become: yes
  vars:
    # --- USTAWIENIA ŚCIEŻEK ---
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    
    # Gdzie na serwerze ANSIBLE ma leżeć backup
    # Używamy /tmp/backups, bo tam łatwiej o uprawnienia
    remote_backup_dir: "/tmp/backups"
    remote_backup_file: "/tmp/backups/agh_backup.tar.gz"
    
    # Gdzie postawić testową instancję
    test_restore_dir: "/tmp/agh_test_instance"

  tasks:
    - name: "--- SEKCJA 1: BACKUP NA MASZYNIE AGH ---"
      block:
        - name: Pakowanie AdGuarda
          archive:
            path: "{{ agh_dir }}"
            dest: "{{ tmp_archive }}"
            format: gz

        - name: Wysyłka na serwer Ansible (Control Node)
          fetch:
            src: "{{ tmp_archive }}"
            dest: "{{ remote_backup_file }}"
            flat: yes # KLUCZOWE: to sprawia, że plik będzie dokładnie tam, gdzie chcemy

      rescue:
        - name: Błąd pakowania
          debug: msg="Nie udało się spakować lub wysłać pliku!"

    - name: "--- SEKCJA 2: TEST NA SERWERZE ANSIBLE ---"
      delegate_to: ansible
      become: yes
      block:
        - name: Przygotowanie folderu testowego
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0755'

        - name: Rozpakowanie backupu
          unarchive:
            src: "{{ remote_backup_file }}"
            dest: "{{ test_restore_dir }}"
            remote_src: yes # Bo plik już tam jest fizycznie

        - name: Uruchomienie AdGuard Home w tle (PORT 3000)
          # Zabijamy stare procesy testowe, żeby nie blokowały portu
          shell: |
            pkill -f "{{ test_restore_dir }}/adguardhome/AdGuardHome" || true
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome > /dev/null 2>&1 &
          async: 10
          poll: 0

        - name: Czekaj na start
          pause: seconds=5

        - name: WERYFIKACJA PANELU WWW
          uri:
            url: "http://localhost:3000"
            status_code: 200
          register: web_test

        - name: Sukces
          debug:
            msg: "DZIAŁA! Backup sprawdzony. Panel pod adresem http://{{ ansible_host }}:3000"

      rescue:
        - name: Powiadomienie o trupie
          debug:
            msg: "ALARM! Coś poszło nie tak przy odtwarzaniu na serwerze Ansible!"
