---
- name: Wielka Przeprowadzka AdGuarda
  hosts: agh
  become: yes
  tasks:
    - name: 1. Pakujemy AdGuarda w wielki worek
      archive:
        path: /opt/adguardhome  # Ścieżka, gdzie masz zainstalowanego AdGuarda
        dest: /tmp/adguard_backup.tar.gz
        format: gz

    - name: 2. Wysyłamy paczkę do bazy (Ansible)
      fetch:
        src: /tmp/adguard_backup.tar.gz
        dest: ./backups/
        flat: yes

- name: Odpalanie AdGuarda na nowym rewirze
  hosts: localhost  # Czyli Twoja maszyna Ansible
  become: yes
  tasks:
    - name: 3. Tworzymy miejsce na dane
      file:
        path: /opt/adguardhome_new
        state: directory

    - name: 4. Rozpakowujemy klocki
      unarchive:
        src: ./backups/adguard_backup.tar.gz
        dest: /opt/adguardhome_new
        extra_opts: [--strip-components=1] # Żeby nie zrobił folderu w folderze

    - name: 5. Odpalamy AdGuarda (Docker to życie)
      docker_container:
        name: adguardhome
        image: adguard/adguardhome
        state: started
        restart_policy: always
        volumes:
          - /opt/adguardhome_new/work:/opt/adguardhome/work
          - /opt/adguardhome_new/conf:/opt/adguardhome/conf
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "80:80/tcp"   # To jest Twój panel pod http://adres_ansible:80
          - "443:443/tcp"
          - "3000:3000/tcp"
