---
- name: Playbook 3 - Backup AdGuard Home i Live Verification
  hosts: agh
  become: yes
  vars:
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    test_restore_dir: "/tmp/agh_test_instance"
    backup_dest_host: "ansible"

  tasks:
    # --- CZĘŚĆ 1: BACKUP NA AGH ---
    - name: Pakowanie plikow AdGuard
      archive:
        path: "{{ agh_dir }}"
        dest: "{{ tmp_archive }}"
        format: gz

    - name: Sciaganie backupu do folderu playbooka
      fetch:
        src: "{{ tmp_archive }}"
        dest: "./agh_final_backup.tar.gz"
        flat: yes

    # --- CZĘŚĆ 2: WERYFIKACJA NA ANSIBLE ---
    - name: Sekcja Weryfikacja
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Przygotowanie folderu testu
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0777'

        - name: Kopiowanie pliku na maszyne docelowa
          copy:
            src: "./agh_final_backup.tar.gz"
            dest: "/tmp/agh_final_backup.tar.gz"

        - name: Rozpakowanie backupu
          unarchive:
            src: "/tmp/agh_final_backup.tar.gz"
            dest: "{{ test_restore_dir }}"
            remote_src: yes

        - name: Uruchomienie testowe AdGuarda (Wymuszenie portu 3000)
          shell: |
            pkill -f "AdGuardHome" || true
            sleep 2
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome -p 3000 > /tmp/agh_test_log.txt 2>&1 &
          async: 30
          poll: 0

        - name: Czekamy dlużej aż port 3000 ożyje
          pause:
            seconds: 20

        - name: TEST WWW (Próba połaczenia)
          wait_for:
            host: 127.0.0.1
            port: 3000
            state: started
            timeout: 15
          register: port_check

        - name: Sukces
          debug:
            msg: "GRATULACJE! Backup zweryfikowany. AdGuard Home dziaia na porcie 3000."

      rescue:
        - name: Wyswietl logi AdGuarda w razie bledu
          command: "tail -n 20 /tmp/agh_test_log.txt"
          register: agh_logs
          ignore_errors: yes

        - name: Powiadomienie o bledzie z logami
          debug:
            msg: 
              - "ALARM! Test WWW padl."
              - "Ostatnie logi AdGuarda: {{ agh_logs.stdout_lines | default('Brak logów') }}"
