---
- name: Instalacja i Konfiguracja AdGuard Home dla AGH_Bieniek
  hosts: agh
  become: yes

  tasks:
    - name: Tworzenie Physical Volume i VG
      lvg:
        vg: adg_vg
        pvs: /dev/sdb,/dev/sdc

    - name: Tworzenie Logical Volume z RAID1
      lvol:
        vg: adg_vg
        lv: adg_lv
        size: 100%FREE
        opts: "--type raid1"

    - name: Formatowanie na system plików ext4
      filesystem:
        fstype: ext4
        dev: /dev/adg_vg/adg_lv

    - name: Tworzenie folderu i montowanie nowego dysku
      mount:
        path: /adguardhome
        src: /dev/adg_vg/adg_lv
        fstype: ext4
        state: mounted

    - name: Pobieranie skryptu instalacyjnego AdGuarda
      get_url:
        url: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
        dest: /tmp/install_agh.sh
        mode: '0755'

    - name: Instalacja AdGuarda (standardowa)
      shell: "/tmp/install_agh.sh"
      ignore_errors: yes

    - name: Zatrzymanie AdGuarda przed migracją
      service:
        name: AdGuardHome
        state: stopped

    - name: Przeniesienie plików do woluminu RAID1
      shell: "cp -r /opt/AdGuardHome/* /adguardhome/"
      args:
        creates: /adguardhome/AdGuardHome

    - name: Reinstalacja serwisu w nowej lokalizacji
      shell: "./AdGuardHome -s install -w /adguardhome"
      args:
        chdir: /adguardhome
      register: service_install
      failed_when: false

    - name: Sprawdzenie czy AdGuard działa
      service:
        name: AdGuardHome
        state: started
        enabled: yes

    - name: Start AdGuarda z nowej lokalizacji
      service:
        name: AdGuardHome
        state: started
        enabled: yes

    - name: Instalacja UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Blokowanie ruchu przychodzącego
      ufw:
        direction: incoming
        policy: deny

    - name: Zezwalanie na SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Zezwalanie na porty AdGuard Home
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: any
      loop:
        - '3000'
        - '80'
        - '443'
        - '53'

    - name: Aktywacja Firewalla na starcie
      ufw:
        state: enabled
