---
- name: Playbook 3 - Backup AdGuard Home i Pewna Weryfikacja
  hosts: agh
  become: yes
  vars:
    agh_dir: "/adguardhome"
    tmp_archive: "/tmp/agh_backup.tar.gz"
    # Adres IP serwera Ansible (kontrolera) - WPISZ SWÓJ IP JEŚLI INNY!
    ansible_server_ip: "192.168.0.42" 
    dest_path: "/tmp/agh_final_backup.tar.gz"
    test_restore_dir: "/tmp/agh_test_instance"

  tasks:
    - name: SEKCJA 1 - BACKUP I WYSYŁKA
      block:
        - name: Pakowanie AdGuarda
          archive:
            path: "{{ agh_dir }}"
            dest: "{{ tmp_archive }}"
            format: gz

        - name: Wysyłka przez SCP (Ominięcie problemów Semaphore)
          # Używamy SSH, żeby wysłać plik bezpośrednio na drugą maszynę
          shell: "scp -o StrictHostKeyChecking=no {{ tmp_archive }} root@{{ ansible_server_ip }}:{{ dest_path }}"
          # UWAGA: To zadziała, jeśli masz wymienione klucze SSH między maszynami!

      rescue:
        - name: Blad backupu
          debug: msg="Nie udalo sie zrobic lub wyslac paczki"

    - name: SEKCJA 2 - WERYFIKACJA NA ANSIBLE
      delegate_to: ansible
      become: yes
      block:
        - name: Przygotowanie folderu testu
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0777'

        - name: Rozpakowanie (Teraz plik NA PEWNO tam bedzie)
          unarchive:
            src: "{{ dest_path }}"
            dest: "{{ test_restore_dir }}"
            remote_src: yes

        - name: Uruchomienie testowe
          shell: |
            pkill -f "AdGuardHome" || true
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome > /dev/null 2>&1 &
          async: 15
          poll: 0

        - name: Czekamy na start
          pause: seconds=10

        - name: TEST WWW
          uri:
            url: "http://127.0.0.1:3000"
            status_code: 200

        - name: Sukces
          debug: msg="WYGRANA! System dziala po odtworzeniu."

      rescue:
        - name: Blad weryfikacji
          debug: msg="Plik dojechał, ale AdGuard nie wstał!"
