---
- name: Playbook 3 - Backup AdGuard Home i Live Verification
  hosts: agh
  become: yes
  vars:
    # Źródło na serwerze AGH
    agh_dir: "/adguardhome"
    tmp_archive_on_agh: "/tmp/agh_backup.tar.gz"
    
    # Cel na serwerze Ansible (gdzie Semaphore go położy)
    # UWAGA: Semaphore często ma problem z pisaniem w /tmp/backups, 
    # więc użyjemy /tmp/ bezpośrednio, bo tam zawsze wolno pisać.
    final_backup_path: "/tmp/agh_final_backup.tar.gz"
    
    # Gdzie testujemy
    test_restore_dir: "/tmp/agh_test_instance"
    backup_dest_host: "ansible"

  tasks:
    # --- ETAP 1: BACKUP NA SERWERZE AGH ---
    - name: Sekcja Backup
      block:
        - name: Pakowanie plików AdGuard Home
          archive:
            path: "{{ agh_dir }}"
            dest: "{{ tmp_archive_on_agh }}"
            format: gz

        - name: Wysylka backupu bezpośrednio do /tmp
          fetch:
            src: "{{ tmp_archive_on_agh }}"
            dest: "{{ final_backup_path }}"
            flat: yes # To MUSI być yes, żeby nie było podfolderów

        - name: Czyszczenie tymczasowego pliku na AGH
          file:
            path: "{{ tmp_archive_on_agh }}"
            state: absent
      rescue:
        - name: Powiadomienie o błędzie pakowania
          debug:
            msg: "BŁĄD: Backup na AGH nie wyszedł."

    # --- ETAP 2: WERYFIKACJA NA SERWERZE ANSIBLE ---
    - name: Sekcja Weryfikacja
      delegate_to: "{{ backup_dest_host }}"
      become: yes
      block:
        - name: Przygotowanie folderu testu
          file:
            path: "{{ test_restore_dir }}"
            state: directory
            mode: '0777'

        - name: Rozpakowanie backupu z konkretnej ścieżki
          unarchive:
            src: "{{ final_backup_path }}"
            dest: "{{ test_restore_dir }}"
            remote_src: yes # Bo plik już tam jest na dysku

        - name: Uruchomienie testowe AdGuarda
          shell: |
            pkill -f "AdGuardHome" || true
            nohup {{ test_restore_dir }}/adguardhome/AdGuardHome -w {{ test_restore_dir }}/adguardhome > /tmp/agh_test_log.txt 2>&1 &
          async: 15
          poll: 0

        - name: Czekamy aż port 3000 ożyje
          pause:
            seconds: 10

        - name: TEST PANELU WWW (kod 200)
          uri:
            url: "http://127.0.0.1:3000"
            status_code: 200
          register: web_test

        - name: Sukces
          debug:
            msg: "WYGRANA! System odtworzony z pliku {{ final_backup_path }}"

      rescue:
        - name: Powiadomienie o błędzie weryfikacji
          debug:
            msg: "ALARM! Odtwarzanie nie zadziałało. Sprawdź czy plik istnieje komendą: ls -l {{ final_backup_path }}"
