---
- name: Kopia zapasowa i odtworzenie konfiguracji AdGuard Home
  hosts: agh
  become: yes
  vars:
    backup_path: "/tmp/agh_backup.tar.gz"

  tasks:
    - name: 1. Pakowanie danych (bez nadrzędnego folderu)
      # Pakujemy zawartość katalogu, aby uniknąć problemów ze strukturą
      shell: "tar -czf {{ backup_path }} -C /adguardhome ."

    - name: 2. Przesłanie pliku na serwer Ansible
      shell: "rsync -avz -e 'ssh -o StrictHostKeyChecking=no' {{ backup_path }} root@192.168.0.42:/tmp/agh_from_remote.tar.gz"
      delegate_to: agh

- name: Przywracanie pełnej konfiguracji na serwerze docelowym
  hosts: ansible
  become: yes
  vars:
    ansible_host_dest: "/opt/adguard_recovery_Bieniek"

  tasks:
    - name: Odtwarzanie systemu i ustawień
      block:
        - name: 3. Przygotowanie czystego folderu
          file:
            path: "{{ ansible_host_dest }}"
            state: absent
        - file:
            path: "{{ ansible_host_dest }}"
            state: directory
            mode: '0755'

        - name: 4. Rozpakowanie paczki
          unarchive:
            src: "/tmp/agh_from_remote.tar.gz"
            dest: "{{ ansible_host_dest }}"
            remote_src: yes

        - name: 5. Poprawka IP w konfiguracji (wymagane do poprawnego startu)
          # Zmieniamy bind_host na 0.0.0.0, żeby AdGuard nie szukał starego IP z serwera AGH
          replace:
            path: "{{ ansible_host_dest }}/AdGuardHome.yaml"
            regexp: 'bind_host: .*'
            replace: 'bind_host: 0.0.0.0'
          ignore_errors: yes

        - name: 6. Rejestracja i start z konkretnym plikiem konfiguracyjnym
          # Flaga -c wskazuje plik konfiguracyjny, a -w katalog roboczy
          shell: |
            ./AdGuardHome -s install -w {{ ansible_host_dest }} -c {{ ansible_host_dest }}/AdGuardHome.yaml
            systemctl restart AdGuardHome
          args:
            chdir: "{{ ansible_host_dest }}"
          failed_when: false

      rescue:
        - name: Powiadomienie Discord
          community.general.discord:
            webhook_id: 1450900992336859249
            webhook_token: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              37303932373334626461343363663132666666633464626634386438613066653963643364343535
              3137616262333132366631653336616136663835326232300a663636323263616238316434623663
              37373232396461643230366264323465326264636534383361393136393561613834323162343637
              6436323463366338620a643631323964656635643166353535643830653866373037663465323964
              65633865366334326136363932643966623233633366343930643339383136656332666463616432
              30613830376133386563633438356531653339356566643333366233356530383935623465303539
              37323133356365626338303062386436383130333837376130356661343762363733393365343838
              36386532613435626466
            username: Semaphore
            content: "❌ Błąd przywracania konfiguracji AdGuard na: {{ inventory_hostname }}"
