---
- name: Automatyzacja Magazynu Danych
  hosts: winsrv
  gather_facts: yes
  vars:
    nazwisko: "Bieniek"
    haslo_userow: "Zaq12wsx"

  tasks:
    - name: Utworzenie Puli Magazynowej i Tieringu
      win_shell: |
        $disks = Get-PhysicalDisk -CanPool $True
        if ($disks) {
            New-StoragePool -FriendlyName "Pula_{{ nazwisko }}" -StorageSubsystemFriendlyName "Windows Storage*" -PhysicalDisks $disks
        }
        New-StorageTier -StoragePoolFriendlyName "Pula_{{ nazwisko }}" -FriendlyName "FastTier" -MediaType SSD -ErrorAction SilentlyContinue
        New-StorageTier -StoragePoolFriendlyName "Pula_{{ nazwisko }}" -FriendlyName "CapacityTier" -MediaType HDD -ErrorAction SilentlyContinue
      failed_when: false

    - name: Utworzenie Virtual Disk i ReFS
      win_shell: |
        $pool = Get-StoragePool -FriendlyName "Pula_{{ nazwisko }}"
        if ($pool -and -not (Get-DriveLetter -DriveLetter F)) {
            $vDisk = New-VirtualDisk -StoragePoolFriendlyName $pool.FriendlyName -FriendlyName "VDisk_{{ nazwisko }}" -UseMaximumSize -ResiliencySettingName Mirror -ProvisioningType Fixed
            $vDisk | Get-Disk | Initialize-Disk -PartitionStyle GPT -PassThru | New-Partition -DriveLetter F -UseMaximumSize | Format-Volume -FileSystem ReFS -NewFileSystemLabel "Dane_{{ nazwisko }}" -Confirm:$false
        }
      failed_when: false

    - name: Utworzenie użytkowników i grup
      block:
        - win_user:
            name: "{{ item.login }}"
            fullname: "{{ item.full }}"
            password: "{{ haslo_userow }}"
            state: present
          loop:
            - { login: 'mromanek', full: 'Marek Romanek' }
            - { login: 'jgula', full: 'Jacek Gula' }
        - win_group:
            name: "Kierownicy_{{ nazwisko }}"
            state: present
        - win_group_membership:
            name: "Kierownicy_{{ nazwisko }}"
            members: [mromanek, jgula]
            state: present

    - name: Folder i Udostepnienie Projekty_Bieniek
      win_file:
        path: 'F:\Projekty'
        state: directory
    - win_share:
        name: "Projekty_{{ nazwisko }}"
        path: 'F:\Projekty'
        full: "Kierownicy_{{ nazwisko }}"
        deny: "Everyone"

    - name: Winget - Odświeżenie źródeł
      win_shell: winget source update
      ignore_errors: yes

    - name: Winget - Instalacja 7zip
      win_shell: winget install --id 7zip.7zip --exact --scope machine --silent --accept-package-agreements --accept-source-agreements
      register: install_7zip
      until: install_7zip is succeeded
      retries: 2
      delay: 10

    - name: Winget - Instalacja Firefox
      win_shell: winget install --id Mozilla.Firefox --exact --scope machine --silent --accept-package-agreements --accept-source-agreements
      ignore_errors: yes

    - name: Winget - Instalacja BIND
      win_shell: winget install --id ISC.Bind --exact --scope machine --silent --accept-package-agreements --accept-source-agreements
      ignore_errors: yes

    - name: Rejestr - blokada usuwania drukarek
      win_shell: |
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"
        if (-not (Test-Path $regPath)) { New-Item -Path $regPath -Force }
        New-ItemProperty -Path $regPath -Name "NoDeletePrinter" -Value 1 -PropertyType DWord -Force
