---
- name: Automatyzacja Magazynu Danych - Wersja Bieniek
  hosts: winsrv
  gather_facts: yes
  vars:
    nazwisko: "Bieniek"
    haslo_userow: "Zaq12wsx"

  tasks:
    # 1. MAGAZYN DANYCH
    - name: Utworzenie Storage Pool (Pula_{{ nazwisko }})
      win_shell: |
        $disks = Get-PhysicalDisk -CanPool $True
        if ($disks) {
            New-StoragePool -FriendlyName "Pula_{{ nazwisko }}" -StorageSubsystemFriendlyName "Windows Storage*" -PhysicalDisks $disks
        }
      failed_when: false

    - name: Konfiguracja Storage Tiers
      win_shell: |
        New-StorageTier -StoragePoolFriendlyName "Pula_{{ nazwisko }}" -FriendlyName "FastTier" -MediaType SSD
        New-StorageTier -StoragePoolFriendlyName "Pula_{{ nazwisko }}" -FriendlyName "CapacityTier" -MediaType HDD
      failed_when: false

    # 2. WIRTUALNY DYSK I REFS
    - name: Utworzenie Virtual Disk i formatowanie ReFS (Litera F)
      win_shell: |
        $pool = Get-StoragePool -FriendlyName "Pula_{{ nazwisko }}"
        if ($pool) {
            $vDisk = New-VirtualDisk -StoragePoolFriendlyName $pool.FriendlyName -FriendlyName "VDisk_{{ nazwisko }}" -UseMaximumSize -ResiliencySettingName Mirror -ProvisioningType Fixed
            $vDisk | Get-Disk | Initialize-Disk -PartitionStyle GPT -PassThru | New-Partition -DriveLetter F -UseMaximumSize | Format-Volume -FileSystem ReFS -NewFileSystemLabel "Dane_{{ nazwisko }}" -Confirm:$false
        }
      failed_when: false

    # 3. UŻYTKOWNICY I GRUPY
    - name: Utworzenie użytkowników Marek i Jacek
      win_user:
        name: "{{ item.login }}"
        fullname: "{{ item.full }}"
        password: "{{ haslo_userow }}"
        state: present
      loop:
        - { login: 'mromanek', full: 'Marek Romanek' }
        - { login: 'jgula', full: 'Jacek Gula' }

    - name: Utworzenie grupy Kierownicy_{{ nazwisko }}
      win_group:
        name: "Kierownicy_{{ nazwisko }}"
        state: present

    - name: Dodanie użytkowników do grupy
      win_group_membership:
        name: "Kierownicy_{{ nazwisko }}"
        members: [mromanek, jgula]
        state: present

    # 4. UDZIAŁ SIECIOWY
    - name: Folder Projekty na dysku F
      win_file:
        path: 'F:\Projekty'
        state: directory

    - name: Udostępnienie katalogu jako Projekty_{{ nazwisko }}
      win_share:
        name: "Projekty_{{ nazwisko }}"
        path: 'F:\Projekty'
        full: "Kierownicy_{{ nazwisko }}"
        deny: "Everyone"

    # 5. INSTALACJA WINGET - WERSJA RATUNKOWA
    - name: Instalacja aplikacji przez Winget (Wymuszona)
      win_shell: |
        # Naprawa błędu regionu i bazy źródeł
        Set-WinHomeLocation -GeoId 191
        winget source reset --force
        
        # Instalacja z wymuszeniem akceptacji wszystkiego
        $apps = @("7zip.7zip", "Mozilla.Firefox", "ISC.BIND")
        foreach ($app in $apps) {
            winget install --id $app --silent --accept-package-agreements --accept-source-agreements --scope machine
        }
        
        # Dodanie BIND do PATH, żeby 'dig' działał w konsoli
        $oldPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
        if ($oldPath -notlike "*BIND9*") {
            [Environment]::SetEnvironmentVariable("Path", $oldPath + ";C:\Program Files\BIND9\bin", "Machine")
        }
      ignore_errors: yes

    # 6. REJESTR - BLOKADA (Przez Shell, żeby nie było błędów ścieżki)
    - name: Rejestr - blokada usuwania drukarek
      win_shell: |
        $path = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"
        if (-not (Test-Path $path)) { New-Item -Path $path -Force }
        New-ItemProperty -Path $path -Name "NoDeletePrinter" -Value 1 -PropertyType DWord -Force
